version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: monochromeboy
      POSTGRES_PASSWORD: anuan
      POSTGRES_DB: artistarea
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "2000:2000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://monochromeboy:anuan@localhost:5432/artistarea
    volumes:
      - .:/usr/src/app

volumes:
  postgres_data:
